export const projects = [
  {
    id: 1,
    title: "Feyer",
    type: "React",
    logo: "/images/feyer.jpeg",
    icon: "/icon/react.svg",
    link: "https://feyer-two.vercel.app/",
  },
  {
    id: 2,
    title: "Mina",
    type: "Angular",
    logo: "/images/mina.png",
    icon: "/icon/angular-icon.svg",
    link: "https://mina-alpha.vercel.app/",
  },
  {
    id: 3,
    title: "Movie-App",
    type: "React",
    logo: "/images/movie-app.png",
    icon: "/icon/react.svg",
    link: "https://now-movie.vercel.app/",
  },
  {
    id: 4,
    title: "Random-Number-Generator",
    type: "React",
    logo: "/images/random-number.jpeg",
    icon: "/icon/react.svg",
    link: "https://random-number-generator-mu.vercel.app/",
  },
  {
    id: 5,
    title: "Millionaire",
    type: "React",
    logo: "/images/millionaire.jpeg",
    icon: "/icon/react.svg",
    link: "https://millionaire-omega.vercel.app/",
  },
  {
    id: 6,
    title: "Videp-Player",
    type: "DOM",
    logo: "/images/video-player.png",
    icon: "/icon/dom.png",
    link: "https://farmanasadov.github.io/Video-Player/",
  },
  {
    id: 7,
    title: "Music-Player",
    type: "DOM",
    logo: "/images/music.png",
    icon: "/icon/dom.png",
    link: "https://farmanasadov.github.io/Music/",
  },
  {
    id: 8,
    title: "Expense-Tracker",
    type: "React",
    logo: "/images/expense-tracker.png",
    icon: "/icon/react.svg",
    link: "https://expense-tracker-theta-roan.vercel.app/",
  },
  {
    id: 9,
    title: "Rock-Paper-Scissors",
    type: "DOM",
    logo: "/images/s-game.png",
    icon: "/icon/dom.png",
    link: "https://rock-paper-scissors-game-pied.vercel.app/",
  },
  {
    id: 10,
    title: "Guessing-Game",
    type: "DOM",
    logo: "/images/Guessing-Game.png",
    icon: "/icon/dom.png",
    link: "https://farmanasadov.github.io/Guessing-Game/",
  },
];
